default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["LEFAT_DB_USER"] %>
  password: <%= ENV["LEFAT_DB_PASSWORD"] %>
  pool: 5
  host: localhost

development:
  <<: *default
  database: <%= ENV["LEFAT_DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["LEFAT_TEST_DATABASE"] %>

